spring:
  application:
    name: microservice-customer
  main:
    allow-bean-definition-overriding: true


  devtools:
    restart:
      enabled: true
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: customer

server:
  port: 8080
  servlet:
    context-path: /customer