spring:
  application:
    name: microservice-customer

  data:
    mongodb:
      uri: mongodb+srv://mkmongouser:Secret@clustermicroservice.fzatn.mongodb.net
      database: customer

server:
  port: 8080
  servlet:
    context-path: /customer