spring:

  data:
    mongodb:
      uri: mongodb+srv://tiger1342:P1HNVoUbPn9zSDiu@cluster0.lsc2s3n.mongodb.net
      database: customer

  application:
    name: microservice-customer

server:
  port: 8080
  servlet:
    context-path: /customer

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, info, metrics

  health:
    show-details: always

  metrics:
    tags:
      application: MonitoringCustomerMicroservice