apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-customer-deployment
  labels:
    app: microservice-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-customer
  template:
    metadata:
      labels:
        app: microservice-customer
    spec:
      containers:
        - name: microservice-customer-container
          image: 877546708265.dkr.ecr.eu-central-1.amazonaws.com/microservice-customer:1.0.0
          ports:
            - containerPort: 8080