apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-deployment
  labels:
    app: microservice-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-customer
  template:
    metadata:
      labels:
        app: microservice-customer
    spec:
      containers:
        - name: microservice-customer-container
          image: microservice-customer:1.0.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-customer-service
spec:
  #Creating a service of type load balancer. Load balancer gets created but takes time to reflect
  type: LoadBalancer
  selector:
    app: microservice-customer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080